"""added email verification, contact_number, address and avatar columns on user

Revision ID: 140db01daaef
Revises: 3457e059799a
Create Date: 2024-08-18 02:09:15.293598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140db01daaef'
down_revision = '3457e059799a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('confirmation_token')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('solved')

    # ### end Alembic commands ###
