"""Add user_name and event_name to RSVP

Revision ID: f3b948bc6009
Revises: 11b814a6f049
Create Date: 2024-08-09 11:56:36.541315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b948bc6009'
down_revision = '11b814a6f049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('event_name', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('unique_user_event', ['user_id', 'event_id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint('unique_user_event', type_='unique')
        batch_op.drop_column('event_name')
        batch_op.drop_column('user_name')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
